### ISSUE TITLE
Error when following the documentation "From your local machine"

### ISSUE THREAD

**Issue by fabientownsend** [felipesere/advisorex#43]
By following these steps:
``` shell
To start your Phoenix server:

Install dependencies with mix deps.get
Create and migrate your database with mix ecto.create && mix ecto.migrate
Install Node.js dependencies with cd assets && npm install
Start Phoenix endpoint with mix phx.server
```

I got this error:
``` shell
==> advisor
Compiling 37 files (.ex)
Generated advisor app
[error] Postgrex.Protocol (#PID<0.4590.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
[error] Postgrex.Protocol (#PID<0.4593.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
```

Then I try (with Felipe) `mix ecto.create`
``` shell
~/D/e/advisorex (master|✔) $ mix ecto.create

17:43:34.602 [error] GenServer #PID<0.193.0> terminating
** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
    (db_connection) lib/db_connection/connection.ex:148: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Advisor.Repo couldn't be created: an exception was raised:
    ** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
        (db_connection) lib/db_connection/connection.ex:148: DBConnection.Connection.connect/2
        (connection) lib/connection.ex:622: Connection.enter_connect/5
        (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
~/D/e/advisorex (master|✔) $
```

**Comment by felipesere** [comment]
Did you have a running Postgres? and was it running on `localhost:5432`?
