### ISSUE TITLE
Crashes the dashboard

### ISSUE THREAD

**Issue by felipesere** [felipesere/advisorex#69]
Advisor crashes if it finds more than one feedback requests from the same person:
```
2017-11-24T13:46:18.589146+00:00 app[web.1]: 13:46:18.588 request_id=0ff0324f-396a-4973-b122-f93a79d63b0c [info] GET /dashboard
2017-11-24T13:46:18.754487+00:00 app[web.1]: 13:46:18.752 request_id=0ff0324f-396a-4973-b122-f93a79d63b0c [info] Sent 500 in 163ms
2017-11-24T13:46:18.769709+00:00 app[web.1]: 13:46:18.769 [error] #PID<0.465.0> running AdvisorWeb.Endpoint terminated
2017-11-24T13:46:18.769712+00:00 app[web.1]: Server: advisorex.herokuapp.com:80 (http)
2017-11-24T13:46:18.769713+00:00 app[web.1]: Request: GET /dashboard
2017-11-24T13:46:18.769714+00:00 app[web.1]: ** (exit) an exception was raised:
2017-11-24T13:46:18.769715+00:00 app[web.1]:     ** (Ecto.MultipleResultsError) expected at most one result but got 2 in query:
2017-11-24T13:46:18.769715+00:00 app[web.1]:
2017-11-24T13:46:18.769716+00:00 app[web.1]: from q in Advisor.Core.Questionnaire,
2017-11-24T13:46:18.769716+00:00 app[web.1]:   where: q.requester_id == ^28,
2017-11-24T13:46:18.769717+00:00 app[web.1]:   select: q,
2017-11-24T13:46:18.769718+00:00 app[web.1]:   preload: [{:advice, [:answers]}, :advice]
2017-11-24T13:46:18.769718+00:00 app[web.1]:
2017-11-24T13:46:18.769719+00:00 app[web.1]:         (ecto) lib/ecto/repo/queryable.ex:73: Ecto.Repo.Queryable.one/4
2017-11-24T13:46:18.769720+00:00 app[web.1]:         (advisor) lib/advisor/core/dashboard/advice_for_me_section.ex:5: Advisor.Core.Dashboard.AdviceForMeSection.advice_for_me_section/1
2017-11-24T13:46:18.769721+00:00 app[web.1]:         (advisor) lib/advisor/core/dashboard/dashboard.ex:10: Advisor.Core.Dashboard.for_user/1
2017-11-24T13:46:18.769725+00:00 app[web.1]:         (advisor) lib/advisor_web/controllers/dashboard_page.ex:10: AdvisorWeb.DashboardPage.index/2
2017-11-24T13:46:18.769725+00:00 app[web.1]:         (advisor) lib/advisor_web/controllers/dashboard_page.ex:1: AdvisorWeb.DashboardPage.action/2
2017-11-24T13:46:18.769740+00:00 app[web.1]:         (advisor) lib/advisor_web/controllers/dashboard_page.ex:1: AdvisorWeb.DashboardPage.phoenix_controller_pipeline/2
2017-11-24T13:46:18.769741+00:00 app[web.1]:         (advisor) lib/advisor_web/endpoint.ex:1: AdvisorWeb.Endpoint.instrument/4
2017-11-24T13:46:18.769742+00:00 app[web.1]:         (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
```

**Comment by felipesere** [comment]
This happens when the same `requester` has two questionnaires open...
